"""CWE mapping from finding descriptions.

Covers 80+ CWEs including the MITRE CWE Top 25 (2024) and all common
web application vulnerability classes mapped to OWASP Top 10 2021.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# CWE database — each entry has id, name, description, severity, owasp_2021
# ---------------------------------------------------------------------------

CWE_DATABASE: dict[str, dict[str, str]] = {
    # -----------------------------------------------------------------------
    # A01:2021 — Broken Access Control
    # -----------------------------------------------------------------------
    "CWE-22": {
        "id": "CWE-22",
        "name": "Path Traversal",
        "description": "Software uses external input to construct a pathname that should be within a restricted directory, but does not properly neutralize sequences such as '..' that can resolve to a location outside of that directory.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-23": {
        "id": "CWE-23",
        "name": "Relative Path Traversal",
        "description": "Software uses external input to construct a pathname that should be restricted but does not properly neutralize relative path sequences.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-35": {
        "id": "CWE-35",
        "name": "Path Traversal: '.../...//'",
        "description": "Software uses external input to construct a pathname but does not properly neutralize '.../...//' sequences.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-59": {
        "id": "CWE-59",
        "name": "Improper Link Resolution Before File Access",
        "description": "Software attempts to access a file based on the filename, but does not properly prevent the filename from identifying a link or shortcut that resolves to an unintended resource.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-200": {
        "id": "CWE-200",
        "name": "Exposure of Sensitive Information to an Unauthorized Actor",
        "description": "Software exposes sensitive information to an actor that is not explicitly authorized to have access to that information.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-201": {
        "id": "CWE-201",
        "name": "Insertion of Sensitive Information Into Sent Data",
        "description": "Software sends data to another actor, but a portion of the data includes sensitive information that should not be accessible to that actor.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-219": {
        "id": "CWE-219",
        "name": "Storage of File with Sensitive Data Under Web Root",
        "description": "Software stores sensitive data under the web document root with insufficient access control, which might make it accessible to untrusted parties.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-264": {
        "id": "CWE-264",
        "name": "Permissions, Privileges, and Access Controls",
        "description": "Weaknesses in this category are related to the management of permissions, privileges, and other security features used to perform access control.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-275": {
        "id": "CWE-275",
        "name": "Permission Issues",
        "description": "Weaknesses in this category are related to improper assignment or handling of permissions.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-276": {
        "id": "CWE-276",
        "name": "Incorrect Default Permissions",
        "description": "Software sets insecure default permissions for files, directories, or other resources during installation or configuration.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-284": {
        "id": "CWE-284",
        "name": "Improper Access Control",
        "description": "Software does not restrict or incorrectly restricts access to a resource from an unauthorized actor.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-285": {
        "id": "CWE-285",
        "name": "Improper Authorization",
        "description": "Software does not perform or incorrectly performs an authorization check when an actor attempts to access a resource or perform an action.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-352": {
        "id": "CWE-352",
        "name": "Cross-Site Request Forgery (CSRF)",
        "description": "Web application does not sufficiently verify whether a well-formed, valid, consistent request was intentionally provided by the user who submitted the request.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-359": {
        "id": "CWE-359",
        "name": "Exposure of Private Personal Information to an Unauthorized Actor",
        "description": "Software does not properly prevent a person's private, personal information from being accessed by actors who either are not explicitly authorized or do not have the implicit consent of the person.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-377": {
        "id": "CWE-377",
        "name": "Insecure Temporary File",
        "description": "Creating and using insecure temporary files can leave application and system data vulnerable to attack.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-402": {
        "id": "CWE-402",
        "name": "Transmission of Private Resources into a New Sphere",
        "description": "Software makes resources available to untrusted parties when those resources are only intended for the software itself or a trusted agent.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-425": {
        "id": "CWE-425",
        "name": "Direct Request (Forced Browsing)",
        "description": "Web application does not adequately enforce appropriate authorization on all restricted URLs, scripts, or files.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-441": {
        "id": "CWE-441",
        "name": "Unintended Proxy or Intermediary (Confused Deputy)",
        "description": "Software receives a request, message, or directive from an upstream component, but does not sufficiently preserve the original source of the request before forwarding.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-497": {
        "id": "CWE-497",
        "name": "Exposure of Sensitive System Information to an Unauthorized Control Sphere",
        "description": "Software does not properly prevent sensitive system information from being accessed by unauthorized actors.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-538": {
        "id": "CWE-538",
        "name": "Insertion of Sensitive Information into Externally-Accessible File or Directory",
        "description": "Software places sensitive information into files or directories that are accessible to actors who are allowed to have access to the files but not the sensitive information.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-540": {
        "id": "CWE-540",
        "name": "Inclusion of Sensitive Information in Source Code",
        "description": "Source code includes sensitive information such as credentials or API keys that could be extracted by an attacker.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-548": {
        "id": "CWE-548",
        "name": "Exposure of Information Through Directory Listing",
        "description": "A directory listing is inappropriately exposed, yielding potentially sensitive information to attackers.",
        "severity": "low",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-552": {
        "id": "CWE-552",
        "name": "Files or Directories Accessible to External Parties",
        "description": "Software makes files or directories accessible to unauthorized actors outside of the intended control sphere.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-566": {
        "id": "CWE-566",
        "name": "Authorization Bypass Through User-Controlled SQL Primary Key",
        "description": "Software uses a database table that includes records that should only be accessible to one user, but allows that user to modify the primary key to access records of other users.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-601": {
        "id": "CWE-601",
        "name": "URL Redirection to Untrusted Site (Open Redirect)",
        "description": "Web application accepts user-controlled input that specifies a link to an external site, and uses that link in a redirect without proper validation.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-639": {
        "id": "CWE-639",
        "name": "Authorization Bypass Through User-Controlled Key",
        "description": "System authorization functionality does not prevent one user from gaining access to another user's data by modifying the key value identifying the data (IDOR).",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-651": {
        "id": "CWE-651",
        "name": "Exposure of WSDL File Containing Sensitive Information",
        "description": "Web service WSDL file is publicly accessible and contains sensitive information about the service implementation.",
        "severity": "low",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-668": {
        "id": "CWE-668",
        "name": "Exposure of Resource to Wrong Sphere",
        "description": "Software exposes a resource to the wrong control sphere, providing unintended actors with inappropriate access to the resource.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-706": {
        "id": "CWE-706",
        "name": "Use of Incorrectly-Resolved Name or Reference",
        "description": "Software uses a name or reference to access a resource, but the name/reference resolves to a resource that is outside of the intended control sphere.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-862": {
        "id": "CWE-862",
        "name": "Missing Authorization",
        "description": "Software does not perform an authorization check when an actor attempts to access a resource or perform an action.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-863": {
        "id": "CWE-863",
        "name": "Incorrect Authorization",
        "description": "Software performs an authorization check when an actor attempts to access a resource, but the check is incorrect.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-913": {
        "id": "CWE-913",
        "name": "Improper Control of Dynamically-Managed Code Resources",
        "description": "Software does not properly restrict reading from or writing to dynamically-managed code resources.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-922": {
        "id": "CWE-922",
        "name": "Insecure Storage of Sensitive Information",
        "description": "Software stores sensitive information without properly limiting read or write access by unauthorized actors.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-942": {
        "id": "CWE-942",
        "name": "Permissive Cross-domain Policy with Untrusted Domains",
        "description": "Software uses a cross-domain policy file that includes domains that should not be trusted.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-1275": {
        "id": "CWE-1275",
        "name": "Sensitive Cookie with Improper SameSite Attribute",
        "description": "SameSite attribute for a sensitive cookie is not set, or is set incorrectly, allowing cross-site request attacks.",
        "severity": "medium",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    # -----------------------------------------------------------------------
    # A02:2021 — Cryptographic Failures
    # -----------------------------------------------------------------------
    "CWE-261": {
        "id": "CWE-261",
        "name": "Weak Encoding for Password",
        "description": "Obscuring a password with a trivial encoding does not protect the password.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-296": {
        "id": "CWE-296",
        "name": "Improper Following of a Certificate's Chain of Trust",
        "description": "Software does not follow or incorrectly follows the chain of trust for a certificate back to a trusted root certificate.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-310": {
        "id": "CWE-310",
        "name": "Cryptographic Issues",
        "description": "Weaknesses in this category are related to the design and implementation of data confidentiality and integrity through cryptography.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-319": {
        "id": "CWE-319",
        "name": "Cleartext Transmission of Sensitive Information",
        "description": "Software transmits sensitive or security-critical data in cleartext in a communication channel that can be sniffed by unauthorized actors.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-321": {
        "id": "CWE-321",
        "name": "Use of Hard-coded Cryptographic Key",
        "description": "Use of a hard-coded cryptographic key significantly increases the possibility that encrypted data may be recovered.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-322": {
        "id": "CWE-322",
        "name": "Key Exchange without Entity Authentication",
        "description": "Software performs a key exchange with an actor without verifying the identity of that actor.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-323": {
        "id": "CWE-323",
        "name": "Reusing a Nonce, Key Pair in Encryption",
        "description": "Nonces should be used only once for a given key pair in cryptographic operations. Reuse may compromise security.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-324": {
        "id": "CWE-324",
        "name": "Use of a Key Past its Expiration Date",
        "description": "Software uses a cryptographic key or password past its expiration date, which diminishes its safety.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-325": {
        "id": "CWE-325",
        "name": "Missing Cryptographic Step",
        "description": "Software does not implement a required step in a cryptographic algorithm, weakening the protection of the associated data.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-326": {
        "id": "CWE-326",
        "name": "Inadequate Encryption Strength",
        "description": "Software stores or transmits sensitive data using an encryption scheme that is theoretically sound, but is not strong enough for the level of protection required.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-327": {
        "id": "CWE-327",
        "name": "Use of a Broken or Risky Cryptographic Algorithm",
        "description": "Use of a broken or risky cryptographic algorithm is an unnecessary risk that may result in exposure of sensitive information.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-328": {
        "id": "CWE-328",
        "name": "Use of Weak Hash",
        "description": "Software uses an algorithm that produces a digest (hash) that does not meet security expectations for a hash function that allows the adversary to reasonably determine the original input.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-329": {
        "id": "CWE-329",
        "name": "Generation of Predictable IV with CBC Mode",
        "description": "Software generates a predictable initialization vector (IV) with Cipher Block Chaining (CBC) mode, weakening encryption.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-330": {
        "id": "CWE-330",
        "name": "Use of Insufficiently Random Values",
        "description": "Software uses insufficiently random numbers or values in a security context that depends on unpredictable numbers.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-331": {
        "id": "CWE-331",
        "name": "Insufficient Entropy",
        "description": "Software uses an algorithm or scheme that produces insufficient entropy, leaving patterns or clusters of values predictable.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-335": {
        "id": "CWE-335",
        "name": "Incorrect Usage of Seeds in Pseudo-Random Number Generator",
        "description": "Software uses a PRNG that is seeded incorrectly, making its output more predictable.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-336": {
        "id": "CWE-336",
        "name": "Same Seed in Pseudo-Random Number Generator",
        "description": "Software uses the same seed each time the PRNG is initialized, causing it to always produce the same output.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-337": {
        "id": "CWE-337",
        "name": "Predictable Seed in Pseudo-Random Number Generator",
        "description": "PRNG is initialized with a predictable seed, such as the process ID or system time.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-338": {
        "id": "CWE-338",
        "name": "Use of Cryptographically Weak Pseudo-Random Number Generator",
        "description": "Software uses a PRNG in a security context, but the PRNG's algorithm is not cryptographically strong.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-340": {
        "id": "CWE-340",
        "name": "Generation of Predictable Numbers or Identifiers",
        "description": "Software uses a scheme that generates numbers or identifiers that are more predictable than required.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-347": {
        "id": "CWE-347",
        "name": "Improper Verification of Cryptographic Signature",
        "description": "Software does not verify, or incorrectly verifies, the cryptographic signature for data.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-523": {
        "id": "CWE-523",
        "name": "Unprotected Transport of Credentials",
        "description": "Login pages do not use adequate measures to protect the user name and password while they are in transit.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-720": {
        "id": "CWE-720",
        "name": "OWASP Top Ten 2007 Category A9 - Insecure Communications",
        "description": "Legacy OWASP category for insecure communications weaknesses.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-757": {
        "id": "CWE-757",
        "name": "Selection of Less-Secure Algorithm During Negotiation (Algorithm Downgrade)",
        "description": "A protocol or implementation can be forced to downgrade to less secure methods or algorithms than required.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-759": {
        "id": "CWE-759",
        "name": "Use of a One-Way Hash without a Salt",
        "description": "Software uses a one-way cryptographic hash against an input that should not be reversible but does not also use a salt.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-760": {
        "id": "CWE-760",
        "name": "Use of a One-Way Hash with a Predictable Salt",
        "description": "Software uses a one-way cryptographic hash with a predictable salt, making precomputation attacks feasible.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-780": {
        "id": "CWE-780",
        "name": "Use of RSA Algorithm without OAEP",
        "description": "Software uses RSA algorithm without Optimal Asymmetric Encryption Padding (OAEP), weakening the encryption.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-818": {
        "id": "CWE-818",
        "name": "Insufficient Transport Layer Protection",
        "description": "Software does not adequately protect data during transmission between parties.",
        "severity": "high",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    "CWE-916": {
        "id": "CWE-916",
        "name": "Use of Password Hash With Insufficient Computational Effort",
        "description": "Software generates a hash for a password but uses a scheme that does not provide a sufficient level of computational effort.",
        "severity": "medium",
        "owasp_2021": "A02:2021 - Cryptographic Failures",
    },
    # -----------------------------------------------------------------------
    # A03:2021 — Injection
    # -----------------------------------------------------------------------
    "CWE-20": {
        "id": "CWE-20",
        "name": "Improper Input Validation",
        "description": "Software does not validate or incorrectly validates input that can affect the control flow or data flow of a program.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-74": {
        "id": "CWE-74",
        "name": "Improper Neutralization of Special Elements in Output Used by a Downstream Component (Injection)",
        "description": "Software constructs all or part of a command, data structure, or record using externally-influenced input without sufficiently neutralizing special elements.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-75": {
        "id": "CWE-75",
        "name": "Failure to Sanitize Special Elements into a Different Plane",
        "description": "Software does not adequately filter special elements that are in a different control plane than the data being processed.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-77": {
        "id": "CWE-77",
        "name": "Command Injection",
        "description": "Software constructs all or part of a command using externally-influenced input but does not neutralize special elements that could modify the intended command.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-78": {
        "id": "CWE-78",
        "name": "Improper Neutralization of Special Elements used in an OS Command (OS Command Injection)",
        "description": "Software constructs all or part of an OS command using externally-influenced input without proper neutralization.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-79": {
        "id": "CWE-79",
        "name": "Improper Neutralization of Input During Web Page Generation (Cross-site Scripting)",
        "description": "Software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output used as a web page served to other users.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-80": {
        "id": "CWE-80",
        "name": "Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)",
        "description": "Software receives input from an upstream component, but does not neutralize or incorrectly neutralizes script-related HTML tags.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-83": {
        "id": "CWE-83",
        "name": "Improper Neutralization of Script in Attributes in a Web Page",
        "description": "Software does not neutralize or incorrectly neutralizes javascript: or other URIs in attributes of HTML elements.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-87": {
        "id": "CWE-87",
        "name": "Improper Neutralization of Alternate XSS Syntax",
        "description": "Software does not neutralize or incorrectly neutralizes user-controllable input for alternate script syntax.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-88": {
        "id": "CWE-88",
        "name": "Improper Neutralization of Argument Delimiters in a Command (Argument Injection)",
        "description": "Software constructs a string for a command to be executed but does not properly delimit the intended arguments.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-89": {
        "id": "CWE-89",
        "name": "Improper Neutralization of Special Elements used in an SQL Command (SQL Injection)",
        "description": "Software constructs all or part of an SQL command using externally-influenced input without proper neutralization.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-90": {
        "id": "CWE-90",
        "name": "Improper Neutralization of Special Elements used in an LDAP Query (LDAP Injection)",
        "description": "Software constructs all or part of an LDAP query using externally-influenced input without proper neutralization.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-91": {
        "id": "CWE-91",
        "name": "XML Injection (aka Blind XPath Injection)",
        "description": "Software does not properly neutralize special elements used in XML, allowing attackers to modify XML syntax and content.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-93": {
        "id": "CWE-93",
        "name": "Improper Neutralization of CRLF Sequences (CRLF Injection)",
        "description": "Software uses CRLF characters in an HTTP context without proper neutralization, allowing header injection.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-94": {
        "id": "CWE-94",
        "name": "Improper Control of Generation of Code (Code Injection)",
        "description": "Software constructs all or part of a code segment using externally-influenced input without proper neutralization.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-95": {
        "id": "CWE-95",
        "name": "Improper Neutralization of Directives in Dynamically Evaluated Code (Eval Injection)",
        "description": "Software receives input that is expected to specify instructions to be executed, but does not neutralize the input properly.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-96": {
        "id": "CWE-96",
        "name": "Improper Neutralization of Directives in Statically Saved Code (Static Code Injection)",
        "description": "Software receives input from an upstream component but does not neutralize code syntax before inserting into an executable resource.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-97": {
        "id": "CWE-97",
        "name": "Improper Neutralization of Server-Side Includes (SSI) Within a Web Page",
        "description": "Software generates a web page that contains SSI directives without proper neutralization of user input.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-98": {
        "id": "CWE-98",
        "name": "Improper Control of Filename for Include/Require Statement in PHP Program",
        "description": "Software allows user input to control or influence which files are included (LFI/RFI).",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-99": {
        "id": "CWE-99",
        "name": "Improper Control of Resource Identifiers (Resource Injection)",
        "description": "Software receives input from an upstream component, but does not restrict or incorrectly restricts the input before it is used as an identifier for a resource.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-113": {
        "id": "CWE-113",
        "name": "Improper Neutralization of CRLF Sequences in HTTP Headers (HTTP Response Splitting)",
        "description": "Software receives data from an upstream component, but does not neutralize CRLF sequences before the data is included in HTTP headers.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-116": {
        "id": "CWE-116",
        "name": "Improper Encoding or Escaping of Output",
        "description": "Software prepares a structured message for communication with another component, but encoding or escaping of the data in the message is either missing or done incorrectly.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-138": {
        "id": "CWE-138",
        "name": "Improper Neutralization of Special Elements",
        "description": "Software receives input from an upstream component, but does not neutralize special elements that could be interpreted in unexpected ways.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-184": {
        "id": "CWE-184",
        "name": "Incomplete List of Disallowed Inputs",
        "description": "Software implements a protection mechanism that relies on a list of inputs that are not allowed, but the list is incomplete.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-470": {
        "id": "CWE-470",
        "name": "Use of Externally-Controlled Input to Select Classes or Code (Unsafe Reflection)",
        "description": "Software uses external input with reflection to select which classes to instantiate or which method to invoke, without proper restriction.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-471": {
        "id": "CWE-471",
        "name": "Modification of Assumed-Immutable Data (MAID)",
        "description": "Software does not properly protect a data element that is assumed to be immutable, allowing an attacker to modify it.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-564": {
        "id": "CWE-564",
        "name": "SQL Injection: Hibernate",
        "description": "Software uses Hibernate to execute a dynamic SQL statement built with user-controlled input that is not properly neutralized.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-610": {
        "id": "CWE-610",
        "name": "Externally Controlled Reference to a Resource in Another Sphere",
        "description": "Software uses external input to access or reference a resource that is in a different control sphere.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-611": {
        "id": "CWE-611",
        "name": "Improper Restriction of XML External Entity Reference",
        "description": "Software processes an XML document that can contain XML entities with URIs that resolve to resources outside the intended sphere of control (XXE).",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-643": {
        "id": "CWE-643",
        "name": "Improper Neutralization of Data within XPath Expressions (XPath Injection)",
        "description": "Software uses external input to dynamically construct an XPath expression without proper neutralization.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-644": {
        "id": "CWE-644",
        "name": "Improper Neutralization of HTTP Headers for Scripting Syntax",
        "description": "Software does not neutralize or incorrectly neutralizes web scripting syntax in HTTP headers.",
        "severity": "medium",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-652": {
        "id": "CWE-652",
        "name": "Improper Neutralization of Data within XQuery Expressions (XQuery Injection)",
        "description": "Software uses external input to dynamically construct an XQuery expression without proper neutralization.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-917": {
        "id": "CWE-917",
        "name": "Improper Neutralization of Special Elements used in an Expression Language Statement (Expression Language Injection)",
        "description": "Software constructs all or part of an expression language statement using externally-influenced input without proper neutralization.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-1336": {
        "id": "CWE-1336",
        "name": "Improper Neutralization of Special Elements Used in a Template Engine (SSTI)",
        "description": "Software uses a template engine to process user-controllable input without proper neutralization, allowing template injection.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    # -----------------------------------------------------------------------
    # A04:2021 — Insecure Design
    # -----------------------------------------------------------------------
    "CWE-209": {
        "id": "CWE-209",
        "name": "Generation of Error Message Containing Sensitive Information",
        "description": "Software generates an error message that includes sensitive information about its environment, users, or associated data.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-256": {
        "id": "CWE-256",
        "name": "Plaintext Storage of a Password",
        "description": "Storing a password in plaintext may result in a system compromise.",
        "severity": "high",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-501": {
        "id": "CWE-501",
        "name": "Trust Boundary Violation",
        "description": "Software mixes trusted and untrusted data in the same data structure or communication channel.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-522": {
        "id": "CWE-522",
        "name": "Insufficiently Protected Credentials",
        "description": "Software transmits or stores authentication credentials, but uses an insecure method susceptible to unauthorized interception or retrieval.",
        "severity": "high",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-602": {
        "id": "CWE-602",
        "name": "Client-Side Enforcement of Server-Side Security",
        "description": "Software relies on client-side checks that can be bypassed by an attacker to enforce server-side security decisions.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-840": {
        "id": "CWE-840",
        "name": "Business Logic Errors",
        "description": "Weaknesses in this category identify flaws in the software business logic that can be exploited.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    # -----------------------------------------------------------------------
    # A05:2021 — Security Misconfiguration
    # -----------------------------------------------------------------------
    "CWE-2": {
        "id": "CWE-2",
        "name": "7PK - Environment",
        "description": "Weaknesses in this category are related to the software's operating environment or configuration.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-11": {
        "id": "CWE-11",
        "name": "ASP.NET Misconfiguration: Creating Debug Binary",
        "description": "Running a debug binary in production can reveal debugging information to attackers.",
        "severity": "low",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-13": {
        "id": "CWE-13",
        "name": "ASP.NET Misconfiguration: Password in Configuration File",
        "description": "Storing a plaintext password in a configuration file enables anyone who can read the file to access the password-protected resource.",
        "severity": "high",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-15": {
        "id": "CWE-15",
        "name": "External Control of System or Configuration Setting",
        "description": "Software allows external control of system or configuration settings, which can lead to disruption or unexpected behavior.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-16": {
        "id": "CWE-16",
        "name": "Configuration",
        "description": "Weaknesses in this category are typically introduced during the configuration of the software.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-260": {
        "id": "CWE-260",
        "name": "Password in Configuration File",
        "description": "Software stores a password in a configuration file that might be accessible to actors who do not need to know the password.",
        "severity": "high",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-315": {
        "id": "CWE-315",
        "name": "Cleartext Storage of Sensitive Information in a Cookie",
        "description": "Software stores sensitive information in a cleartext cookie.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-520": {
        "id": "CWE-520",
        "name": ".NET Misconfiguration: Use of Impersonation",
        "description": "Allowing an application to use impersonation and access resources using the identity of the client.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-526": {
        "id": "CWE-526",
        "name": "Cleartext Storage of Sensitive Information in an Environment Variable",
        "description": "Software stores sensitive information in a cleartext environment variable.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-537": {
        "id": "CWE-537",
        "name": "Java Runtime Error Message Containing Sensitive Information",
        "description": "Java runtime error messages can include detailed information about the application environment.",
        "severity": "low",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-541": {
        "id": "CWE-541",
        "name": "Inclusion of Sensitive Information in an Include File",
        "description": "Software includes sensitive information in a file that is accessible to actors who are not authorized.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-547": {
        "id": "CWE-547",
        "name": "Use of Hard-coded, Security-relevant Constants",
        "description": "Software uses hard-coded constants for security-relevant operations like cryptographic functions.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-614": {
        "id": "CWE-614",
        "name": "Sensitive Cookie in HTTPS Session Without 'Secure' Attribute",
        "description": "A cookie containing sensitive data is set without the Secure flag, potentially exposing it over unencrypted connections.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-756": {
        "id": "CWE-756",
        "name": "Missing Custom Error Page",
        "description": "Software does not return custom error pages to the user, potentially exposing sensitive implementation details.",
        "severity": "low",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-776": {
        "id": "CWE-776",
        "name": "Improper Restriction of Recursive Entity References in DTDs (XML Entity Expansion)",
        "description": "Software uses XML but does not properly restrict recursive entity references, allowing billion-laughs or similar attacks.",
        "severity": "high",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-1004": {
        "id": "CWE-1004",
        "name": "Sensitive Cookie Without 'HttpOnly' Flag",
        "description": "A cookie containing sensitive data is set without the HttpOnly flag, making it accessible to client-side scripts.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    # -----------------------------------------------------------------------
    # A06:2021 — Vulnerable and Outdated Components
    # -----------------------------------------------------------------------
    "CWE-937": {
        "id": "CWE-937",
        "name": "OWASP Top Ten 2013 Category A9 - Using Components with Known Vulnerabilities",
        "description": "Software uses a third-party component with known vulnerabilities.",
        "severity": "high",
        "owasp_2021": "A06:2021 - Vulnerable and Outdated Components",
    },
    "CWE-1035": {
        "id": "CWE-1035",
        "name": "OWASP Top Ten 2017 Category A9 - Using Components with Known Vulnerabilities",
        "description": "Software uses third-party components with known security vulnerabilities.",
        "severity": "high",
        "owasp_2021": "A06:2021 - Vulnerable and Outdated Components",
    },
    "CWE-1104": {
        "id": "CWE-1104",
        "name": "Use of Unmaintained Third Party Components",
        "description": "Software uses third-party components that are no longer maintained, receiving no patches for new vulnerabilities.",
        "severity": "medium",
        "owasp_2021": "A06:2021 - Vulnerable and Outdated Components",
    },
    # -----------------------------------------------------------------------
    # A07:2021 — Identification and Authentication Failures
    # -----------------------------------------------------------------------
    "CWE-255": {
        "id": "CWE-255",
        "name": "Credentials Management Errors",
        "description": "Weaknesses in this category are related to the management of credentials.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-287": {
        "id": "CWE-287",
        "name": "Improper Authentication",
        "description": "Software does not prove or insufficiently proves that a claimed identity is correct when performing authentication.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-288": {
        "id": "CWE-288",
        "name": "Authentication Bypass Using an Alternate Path or Channel",
        "description": "Software requires authentication, but an alternate path or channel exists that does not require authentication.",
        "severity": "critical",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-290": {
        "id": "CWE-290",
        "name": "Authentication Bypass by Spoofing",
        "description": "Software performs authentication based on the name/identity of a resource being accessed, which can be spoofed.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-294": {
        "id": "CWE-294",
        "name": "Authentication Bypass by Capture-replay",
        "description": "Software uses an authentication protocol susceptible to capture-replay attacks.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-295": {
        "id": "CWE-295",
        "name": "Improper Certificate Validation",
        "description": "Software does not validate, or incorrectly validates, a certificate, allowing man-in-the-middle attacks.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-297": {
        "id": "CWE-297",
        "name": "Improper Validation of Certificate with Host Mismatch",
        "description": "Software communicates with a host that provides a certificate, but does not verify that the certificate is actually associated with that host.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-306": {
        "id": "CWE-306",
        "name": "Missing Authentication for Critical Function",
        "description": "Software does not perform any authentication for functionality that requires a provable user identity.",
        "severity": "critical",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-307": {
        "id": "CWE-307",
        "name": "Improper Restriction of Excessive Authentication Attempts",
        "description": "Software does not implement sufficient anti-automation to prevent brute-force credential attacks.",
        "severity": "medium",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-384": {
        "id": "CWE-384",
        "name": "Session Fixation",
        "description": "Software does not properly regenerate session tokens after authentication, allowing session fixation attacks.",
        "severity": "high",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-521": {
        "id": "CWE-521",
        "name": "Weak Password Requirements",
        "description": "Software does not require that users provide sufficiently strong passwords.",
        "severity": "medium",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-613": {
        "id": "CWE-613",
        "name": "Insufficient Session Expiration",
        "description": "Software does not sufficiently limit the lifetime of a session, allowing attackers to use old session credentials.",
        "severity": "medium",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-620": {
        "id": "CWE-620",
        "name": "Unverified Password Change",
        "description": "Software allows password changes without verifying the current password, enabling unauthorized changes.",
        "severity": "medium",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-640": {
        "id": "CWE-640",
        "name": "Weak Password Recovery Mechanism for Forgotten Password",
        "description": "Software contains a mechanism for users to recover or change their passwords without sufficient identity verification.",
        "severity": "medium",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    "CWE-798": {
        "id": "CWE-798",
        "name": "Use of Hard-coded Credentials",
        "description": "Software contains hard-coded credentials for inbound or outbound authentication, enabling attackers to bypass authentication.",
        "severity": "critical",
        "owasp_2021": "A07:2021 - Identification and Authentication Failures",
    },
    # -----------------------------------------------------------------------
    # A08:2021 — Software and Data Integrity Failures
    # -----------------------------------------------------------------------
    "CWE-345": {
        "id": "CWE-345",
        "name": "Insufficient Verification of Data Authenticity",
        "description": "Software does not sufficiently verify the origin or authenticity of data, enabling spoofed data to be accepted.",
        "severity": "medium",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-353": {
        "id": "CWE-353",
        "name": "Missing Support for Integrity Check",
        "description": "Software uses a transmission protocol that does not include integrity checking of the data.",
        "severity": "medium",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-426": {
        "id": "CWE-426",
        "name": "Untrusted Search Path",
        "description": "Software searches for critical resources using a search path that can be controlled by an attacker.",
        "severity": "high",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-434": {
        "id": "CWE-434",
        "name": "Unrestricted Upload of File with Dangerous Type",
        "description": "Software allows the attacker to upload or transfer files of dangerous types that can be automatically processed.",
        "severity": "critical",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-502": {
        "id": "CWE-502",
        "name": "Deserialization of Untrusted Data",
        "description": "Software deserializes untrusted data without sufficiently verifying that the resulting data is valid, enabling RCE or other attacks.",
        "severity": "critical",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-565": {
        "id": "CWE-565",
        "name": "Reliance on Cookies without Validation and Integrity Checking",
        "description": "Software relies on cookies without verifying that the data in those cookies is correct.",
        "severity": "medium",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-784": {
        "id": "CWE-784",
        "name": "Reliance on Cookies without Validation and Integrity Checking in a Security Decision",
        "description": "Software uses cookies for security decisions without verifying their integrity.",
        "severity": "high",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-829": {
        "id": "CWE-829",
        "name": "Inclusion of Functionality from Untrusted Control Sphere",
        "description": "Software imports or includes functionality from a source outside of the intended control sphere.",
        "severity": "high",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    "CWE-915": {
        "id": "CWE-915",
        "name": "Improperly Controlled Modification of Dynamically-Determined Object Attributes",
        "description": "Software receives input to define or modify an object's attributes but does not properly restrict which attributes can be modified (mass assignment).",
        "severity": "high",
        "owasp_2021": "A08:2021 - Software and Data Integrity Failures",
    },
    # -----------------------------------------------------------------------
    # A09:2021 — Security Logging and Monitoring Failures
    # -----------------------------------------------------------------------
    "CWE-117": {
        "id": "CWE-117",
        "name": "Improper Output Neutralization for Logs",
        "description": "Software does not neutralize or incorrectly neutralizes output that is written to logs, enabling log injection.",
        "severity": "medium",
        "owasp_2021": "A09:2021 - Security Logging and Monitoring Failures",
    },
    "CWE-223": {
        "id": "CWE-223",
        "name": "Omission of Security-relevant Information",
        "description": "Software does not record or display information needed to identify the source or nature of an attack.",
        "severity": "medium",
        "owasp_2021": "A09:2021 - Security Logging and Monitoring Failures",
    },
    "CWE-532": {
        "id": "CWE-532",
        "name": "Insertion of Sensitive Information into Log File",
        "description": "Software writes sensitive information to log files that are accessible to unauthorized actors.",
        "severity": "medium",
        "owasp_2021": "A09:2021 - Security Logging and Monitoring Failures",
    },
    "CWE-778": {
        "id": "CWE-778",
        "name": "Insufficient Logging",
        "description": "Software does not log critical events or does not log enough detail about events to enable detection of attacks.",
        "severity": "medium",
        "owasp_2021": "A09:2021 - Security Logging and Monitoring Failures",
    },
    # -----------------------------------------------------------------------
    # A10:2021 — Server-Side Request Forgery (SSRF)
    # -----------------------------------------------------------------------
    "CWE-918": {
        "id": "CWE-918",
        "name": "Server-Side Request Forgery (SSRF)",
        "description": "Web server receives a URL or similar request from an upstream component and retrieves the contents of that URL, but does not ensure that the request is being sent to the expected destination.",
        "severity": "high",
        "owasp_2021": "A10:2021 - Server-Side Request Forgery (SSRF)",
    },
    # -----------------------------------------------------------------------
    # Additional CWEs from MITRE Top 25 (2024) not yet covered
    # -----------------------------------------------------------------------
    "CWE-119": {
        "id": "CWE-119",
        "name": "Improper Restriction of Operations within the Bounds of a Memory Buffer",
        "description": "Software performs operations on a memory buffer, but it can read from or write to a memory location outside the intended boundary of the buffer.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-125": {
        "id": "CWE-125",
        "name": "Out-of-bounds Read",
        "description": "Software reads data past the end, or before the beginning, of the intended buffer.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-190": {
        "id": "CWE-190",
        "name": "Integer Overflow or Wraparound",
        "description": "Software performs a calculation that can produce an integer overflow or wraparound, leading to unexpected behavior or security weakness.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-269": {
        "id": "CWE-269",
        "name": "Improper Privilege Management",
        "description": "Software does not properly assign, modify, track, or check privileges for an actor, creating an unintended sphere of control.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-362": {
        "id": "CWE-362",
        "name": "Concurrent Execution Using Shared Resource with Improper Synchronization (Race Condition)",
        "description": "Software contains a code sequence that can run concurrently with other code, allowing modification of shared resources in unexpected ways.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-416": {
        "id": "CWE-416",
        "name": "Use After Free",
        "description": "Software references memory after it has been freed, which can lead to crashes, data corruption, or code execution.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-476": {
        "id": "CWE-476",
        "name": "NULL Pointer Dereference",
        "description": "Software dereferences a pointer that it expects to be valid, but is NULL, leading to crashes.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-787": {
        "id": "CWE-787",
        "name": "Out-of-bounds Write",
        "description": "Software writes data past the end, or before the beginning, of the intended buffer, potentially leading to code execution.",
        "severity": "critical",
        "owasp_2021": "A03:2021 - Injection",
    },
    # -----------------------------------------------------------------------
    # Additional CWEs for expanded scanner coverage
    # -----------------------------------------------------------------------
    "CWE-1321": {
        "id": "CWE-1321",
        "name": "Improperly Controlled Modification of Object Prototype Attributes (Prototype Pollution)",
        "description": "Software receives input from an upstream component that specifies attributes to be used to modify an object's prototype, leading to prototype pollution.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
    "CWE-1385": {
        "id": "CWE-1385",
        "name": "Missing Origin Validation in WebSockets",
        "description": "Software does not validate the origin of incoming WebSocket connections, allowing cross-site WebSocket hijacking.",
        "severity": "high",
        "owasp_2021": "A01:2021 - Broken Access Control",
    },
    "CWE-444": {
        "id": "CWE-444",
        "name": "Inconsistent Interpretation of HTTP Requests (HTTP Request Smuggling)",
        "description": "HTTP intermediaries (proxies, firewalls) interpret HTTP requests differently, allowing request smuggling attacks.",
        "severity": "high",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-1022": {
        "id": "CWE-1022",
        "name": "Use of Web Link to Untrusted Target with window.opener Access (Clickjacking/Tabnabbing)",
        "description": "Web application generates links to untrusted targets without rel=noopener, allowing reverse tabnabbing.",
        "severity": "medium",
        "owasp_2021": "A05:2021 - Security Misconfiguration",
    },
    "CWE-770": {
        "id": "CWE-770",
        "name": "Allocation of Resources Without Limits or Throttling",
        "description": "Software does not properly restrict resource allocation, allowing denial of service through resource exhaustion.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-400": {
        "id": "CWE-400",
        "name": "Uncontrolled Resource Consumption",
        "description": "Software does not properly control the allocation and maintenance of a limited resource, enabling resource exhaustion.",
        "severity": "medium",
        "owasp_2021": "A04:2021 - Insecure Design",
    },
    "CWE-943": {
        "id": "CWE-943",
        "name": "Improper Neutralization of Special Elements in Data Query Logic (NoSQL Injection)",
        "description": "Software constructs data query logic from user input without proper neutralization, enabling NoSQL injection.",
        "severity": "high",
        "owasp_2021": "A03:2021 - Injection",
    },
}


# ---------------------------------------------------------------------------
# Keyword → CWE mapping for text-based detection from finding titles/descriptions
# ---------------------------------------------------------------------------

VULN_CWE_MAP: dict[str, dict[str, str]] = {
    # A03 — Injection
    "sqli": {"id": "CWE-89", "name": "SQL Injection"},
    "sql injection": {"id": "CWE-89", "name": "SQL Injection"},
    "xss": {"id": "CWE-79", "name": "Cross-site Scripting"},
    "cross-site scripting": {"id": "CWE-79", "name": "Cross-site Scripting"},
    "csrf": {"id": "CWE-352", "name": "Cross-Site Request Forgery"},
    "cross-site request forgery": {"id": "CWE-352", "name": "Cross-Site Request Forgery"},
    "ssrf": {"id": "CWE-918", "name": "Server-Side Request Forgery"},
    "server-side request forgery": {"id": "CWE-918", "name": "Server-Side Request Forgery"},
    "lfi": {"id": "CWE-98", "name": "Improper Control of Filename for Include"},
    "local file inclusion": {"id": "CWE-98", "name": "Improper Control of Filename for Include"},
    "rfi": {"id": "CWE-98", "name": "Improper Control of Filename for Include"},
    "remote file inclusion": {"id": "CWE-98", "name": "Improper Control of Filename for Include"},
    "ssti": {"id": "CWE-1336", "name": "Template Injection"},
    "server-side template injection": {"id": "CWE-1336", "name": "Template Injection"},
    "template injection": {"id": "CWE-1336", "name": "Template Injection"},
    "idor": {"id": "CWE-639", "name": "Authorization Bypass Through User-Controlled Key"},
    "insecure direct object reference": {
        "id": "CWE-639",
        "name": "Authorization Bypass Through User-Controlled Key",
    },
    "command injection": {"id": "CWE-78", "name": "OS Command Injection"},
    "os command injection": {"id": "CWE-78", "name": "OS Command Injection"},
    "xxe": {"id": "CWE-611", "name": "XML External Entity"},
    "xml external entity": {"id": "CWE-611", "name": "XML External Entity"},
    "deserialization": {"id": "CWE-502", "name": "Deserialization of Untrusted Data"},
    "insecure deserialization": {"id": "CWE-502", "name": "Deserialization of Untrusted Data"},
    "default credentials": {"id": "CWE-798", "name": "Use of Hard-coded Credentials"},
    "hard-coded credentials": {"id": "CWE-798", "name": "Use of Hard-coded Credentials"},
    "hardcoded credentials": {"id": "CWE-798", "name": "Use of Hard-coded Credentials"},
    "information disclosure": {"id": "CWE-200", "name": "Information Exposure"},
    "information exposure": {"id": "CWE-200", "name": "Information Exposure"},
    "sensitive data exposure": {"id": "CWE-200", "name": "Information Exposure"},
    "misconfiguration": {"id": "CWE-16", "name": "Configuration"},
    "security misconfiguration": {"id": "CWE-16", "name": "Configuration"},
    "cors": {"id": "CWE-942", "name": "Permissive Cross-domain Policy"},
    "cors misconfiguration": {"id": "CWE-942", "name": "Permissive Cross-domain Policy"},
    "open redirect": {"id": "CWE-601", "name": "URL Redirection to Untrusted Site"},
    "url redirection": {"id": "CWE-601", "name": "URL Redirection to Untrusted Site"},
    "path traversal": {"id": "CWE-22", "name": "Path Traversal"},
    "directory traversal": {"id": "CWE-22", "name": "Path Traversal"},
    "authentication bypass": {"id": "CWE-287", "name": "Improper Authentication"},
    "improper authentication": {"id": "CWE-287", "name": "Improper Authentication"},
    "broken authentication": {"id": "CWE-287", "name": "Improper Authentication"},
    # A01 — Broken Access Control
    "broken access control": {"id": "CWE-284", "name": "Improper Access Control"},
    "improper access control": {"id": "CWE-284", "name": "Improper Access Control"},
    "missing authorization": {"id": "CWE-862", "name": "Missing Authorization"},
    "incorrect authorization": {"id": "CWE-863", "name": "Incorrect Authorization"},
    "forced browsing": {"id": "CWE-425", "name": "Direct Request (Forced Browsing)"},
    "directory listing": {"id": "CWE-548", "name": "Directory Listing"},
    "privilege escalation": {"id": "CWE-269", "name": "Improper Privilege Management"},
    "session fixation": {"id": "CWE-384", "name": "Session Fixation"},
    # A02 — Cryptographic Failures
    "weak cipher": {"id": "CWE-326", "name": "Inadequate Encryption Strength"},
    "weak encryption": {"id": "CWE-326", "name": "Inadequate Encryption Strength"},
    "weak cryptography": {"id": "CWE-327", "name": "Use of a Broken or Risky Cryptographic Algorithm"},
    "broken crypto": {"id": "CWE-327", "name": "Use of a Broken or Risky Cryptographic Algorithm"},
    "cleartext transmission": {"id": "CWE-319", "name": "Cleartext Transmission of Sensitive Information"},
    "missing https": {"id": "CWE-319", "name": "Cleartext Transmission of Sensitive Information"},
    "weak hash": {"id": "CWE-328", "name": "Use of Weak Hash"},
    "md5": {"id": "CWE-328", "name": "Use of Weak Hash"},
    "sha1": {"id": "CWE-328", "name": "Use of Weak Hash"},
    "weak password hash": {"id": "CWE-916", "name": "Password Hash With Insufficient Computational Effort"},
    "missing salt": {"id": "CWE-759", "name": "Use of a One-Way Hash without a Salt"},
    "insufficient entropy": {"id": "CWE-331", "name": "Insufficient Entropy"},
    "weak random": {"id": "CWE-330", "name": "Use of Insufficiently Random Values"},
    "predictable token": {"id": "CWE-330", "name": "Use of Insufficiently Random Values"},
    "certificate validation": {"id": "CWE-295", "name": "Improper Certificate Validation"},
    "ssl": {"id": "CWE-295", "name": "Improper Certificate Validation"},
    "tls": {"id": "CWE-295", "name": "Improper Certificate Validation"},
    # A04 — Insecure Design
    "business logic": {"id": "CWE-840", "name": "Business Logic Errors"},
    "race condition": {"id": "CWE-362", "name": "Race Condition"},
    "trust boundary": {"id": "CWE-501", "name": "Trust Boundary Violation"},
    "error message": {"id": "CWE-209", "name": "Error Message Containing Sensitive Information"},
    "verbose error": {"id": "CWE-209", "name": "Error Message Containing Sensitive Information"},
    "stack trace": {"id": "CWE-209", "name": "Error Message Containing Sensitive Information"},
    # A05 — Security Misconfiguration
    "debug mode": {"id": "CWE-11", "name": "Debug Binary in Production"},
    "missing security header": {"id": "CWE-16", "name": "Configuration"},
    "missing httponly": {"id": "CWE-1004", "name": "Sensitive Cookie Without 'HttpOnly' Flag"},
    "missing secure flag": {"id": "CWE-614", "name": "Sensitive Cookie Without 'Secure' Attribute"},
    "cookie without secure": {"id": "CWE-614", "name": "Sensitive Cookie Without 'Secure' Attribute"},
    "cookie without httponly": {"id": "CWE-1004", "name": "Sensitive Cookie Without 'HttpOnly' Flag"},
    "samesite": {"id": "CWE-1275", "name": "Sensitive Cookie with Improper SameSite Attribute"},
    "xml entity expansion": {"id": "CWE-776", "name": "XML Entity Expansion"},
    # A06 — Vulnerable and Outdated Components
    "outdated component": {"id": "CWE-1104", "name": "Use of Unmaintained Third Party Components"},
    "known vulnerability": {"id": "CWE-1035", "name": "Using Components with Known Vulnerabilities"},
    "outdated software": {"id": "CWE-1104", "name": "Use of Unmaintained Third Party Components"},
    "vulnerable component": {"id": "CWE-937", "name": "Using Components with Known Vulnerabilities"},
    "outdated library": {"id": "CWE-1104", "name": "Use of Unmaintained Third Party Components"},
    # A07 — Identification and Authentication Failures
    "brute force": {"id": "CWE-307", "name": "Improper Restriction of Excessive Authentication Attempts"},
    "weak password": {"id": "CWE-521", "name": "Weak Password Requirements"},
    "session expiration": {"id": "CWE-613", "name": "Insufficient Session Expiration"},
    "password recovery": {"id": "CWE-640", "name": "Weak Password Recovery Mechanism"},
    "missing authentication": {"id": "CWE-306", "name": "Missing Authentication for Critical Function"},
    # A08 — Software and Data Integrity Failures
    "file upload": {"id": "CWE-434", "name": "Unrestricted Upload of File with Dangerous Type"},
    "unrestricted upload": {"id": "CWE-434", "name": "Unrestricted Upload of File with Dangerous Type"},
    "mass assignment": {"id": "CWE-915", "name": "Mass Assignment"},
    "prototype pollution": {"id": "CWE-915", "name": "Mass Assignment"},
    # A09 — Security Logging and Monitoring Failures
    "log injection": {"id": "CWE-117", "name": "Improper Output Neutralization for Logs"},
    "insufficient logging": {"id": "CWE-778", "name": "Insufficient Logging"},
    "sensitive data in log": {"id": "CWE-532", "name": "Sensitive Information into Log File"},
    # Injection variants
    "ldap injection": {"id": "CWE-90", "name": "LDAP Injection"},
    "xpath injection": {"id": "CWE-643", "name": "XPath Injection"},
    "xquery injection": {"id": "CWE-652", "name": "XQuery Injection"},
    "code injection": {"id": "CWE-94", "name": "Code Injection"},
    "eval injection": {"id": "CWE-95", "name": "Eval Injection"},
    "crlf injection": {"id": "CWE-93", "name": "CRLF Injection"},
    "http response splitting": {"id": "CWE-113", "name": "HTTP Response Splitting"},
    "header injection": {"id": "CWE-113", "name": "HTTP Response Splitting"},
    "expression language injection": {"id": "CWE-917", "name": "Expression Language Injection"},
    "el injection": {"id": "CWE-917", "name": "Expression Language Injection"},
    "argument injection": {"id": "CWE-88", "name": "Argument Injection"},
    "ssi injection": {"id": "CWE-97", "name": "SSI Injection"},
    "xml injection": {"id": "CWE-91", "name": "XML Injection"},
    "unsafe reflection": {"id": "CWE-470", "name": "Unsafe Reflection"},
    "input validation": {"id": "CWE-20", "name": "Improper Input Validation"},
    "improper input": {"id": "CWE-20", "name": "Improper Input Validation"},
}


def get_cwe_info(title: str, description: str = "") -> dict[str, str] | None:
    """Find CWE mapping from finding title and description.

    Searches through known vulnerability keywords in the combined title and description.
    Returns the first matching CWE entry with ``id`` and ``name`` keys, or ``None``.
    """
    text = f"{title} {description}".lower()
    for keyword, cwe_info in VULN_CWE_MAP.items():
        if keyword in text:
            return cwe_info
    return None


def get_cwe_details(cwe_id: str) -> dict[str, str] | None:
    """Return full CWE details from the database by CWE ID.

    Returns a dict with ``id``, ``name``, ``description``, ``severity``, and
    ``owasp_2021`` keys, or ``None`` if the CWE is not in the database.
    """
    return CWE_DATABASE.get(cwe_id)
